# Site
repository: hfurkanbozkurt/hfurkanbozkurt.github.io
favicon: images/favicon.ico

# Personal info
name: H. Furkan Bozkurt
title: Machine Learning Engineer
email: hfurkanbozkurt@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  hfurkanbozkurt
linkedin_username: hfurkanbozkurt
scholar_username: hyTX6wsAAAAJ&

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Furkan. I am a Machine Learning Engineer working for SageMaker, Amazon Web Services. I am passionate about artificial intelligence, reinforcement learning, hyperperameter optimization and automated machine learning. I highly value open source software and democratizing artificial intelligence for everyone.

  Besides my professional activities, I enjoy playing and watching basketball, travelling whenever I can and try local street food, cook for my loved ones, and enjoy riding my bike on a nice Berlin sunset.

  Click [here](resources/CV.pdf){:target="_blank"} for my CV in pdf form and feel free to send me an [email](mailto:hfurkanbozkurt@gmail.com).

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
